# Generated by Django 2.2.7 on 2019-11-07 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEquipamento', models.CharField(max_length=20)),
                ('descricaoEquipamento', models.TextField()),
                ('registroEquipamento', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePaciente', models.CharField(max_length=50)),
                ('matriculaPaciente', models.CharField(max_length=20)),
                ('idadePaciente', models.IntegerField()),
                ('sexoPaciente', models.CharField(choices=[['F', 'Feminino'], ['M', 'Masculino'], ['N', 'Nenhuma das opções']], default='F', max_length=1)),
                ('telefonePaciente', models.CharField(max_length=20)),
                ('telefoneResponsavelPaciente', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProcedimento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVacina', models.CharField(max_length=20)),
                ('descricaoVacina', models.TextField()),
                ('criacaoVacina', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricaoAtendimento', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='sisgen.Paciente')),
                ('vacinacao', models.ManyToManyField(to='sisgen.Vacina')),
            ],
        ),
    ]
