# Generated by Django 2.2.3 on 2019-11-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgen', '0002_auto_20191114_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='procedimento',
            field=models.ManyToManyField(to='sisgen.Procedimento', verbose_name='Procedimento(s) realizado(s):'),
        ),
    ]
