# Generated by Django 2.2.3 on 2019-11-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgen', '0003_atendimento_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='turmaPaciente',
            field=models.CharField(default='Turma 1', max_length=20, verbose_name='Turma:'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='procedimento',
            field=models.ManyToManyField(blank=True, to='sisgen.Procedimento', verbose_name='Procedimento(s) realizado(s):'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='vacinacao',
            field=models.ManyToManyField(blank=True, to='sisgen.Vacina', verbose_name='Vacinação do Paciente:'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefoneResponsavelPaciente',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável:'),
        ),
    ]
