# Generated by Django 2.2.3 on 2019-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgen', '0005_auto_20191121_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='turmaPaciente',
            field=models.CharField(blank=True, max_length=20, verbose_name='Turma:'),
        ),
    ]
