# Generated by Django 2.2.3 on 2019-11-26 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sisgen', '0006_auto_20191121_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(verbose_name='De:')),
                ('dataFim', models.DateField(default=django.utils.timezone.now, verbose_name='Até:')),
                ('atendimentos', models.ManyToManyField(blank=True, to='sisgen.Atendimento', verbose_name='Atendimentos:')),
            ],
        ),
    ]
