# Generated by Django 2.2.3 on 2019-12-08 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgen', '0007_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data/Hora:'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='registroEquipamento',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Registro:'),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='criacaoVacina',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Registro:'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
